
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Oct 04 01:20:48 CEST 2009
//----------------------------------------------------

package culebra.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int PLUSPLUS = 49;
  public static final int ASSIG = 51;
  public static final int SUBSASSIG = 53;
  public static final int STR = 26;
  public static final int GREAT = 43;
  public static final int CASE = 5;
  public static final int INTEGER = 2;
  public static final int LPAREN = 30;
  public static final int CONTINUE = 20;
  public static final int FLT = 27;
  public static final int INT = 25;
  public static final int PRINTLN = 54;
  public static final int LESS = 42;
  public static final int MINUS = 39;
  public static final int FOR = 15;
  public static final int RPAREN = 31;
  public static final int ESCRIBEINT = 12;
  public static final int DEFINE = 6;
  public static final int NOT = 48;
  public static final int AND = 46;
  public static final int SEMICOLON = 35;
  public static final int TMP = 24;
  public static final int OR = 47;
  public static final int FLUSH = 10;
  public static final int DIV = 41;
  public static final int PLUS = 38;
  public static final int TYPEDEF = 23;
  public static final int ADDASSIG = 52;
  public static final int MAIN = 17;
  public static final int IF = 21;
  public static final int DOT = 57;
  public static final int ID = 4;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 50;
  public static final int RETURN = 19;
  public static final int EQUAL = 44;
  public static final int error = 1;
  public static final int MUL = 40;
  public static final int COMA = 34;
  public static final int LCURLY = 32;
  public static final int BREAK = 7;
  public static final int VOID = 28;
  public static final int SWITCH = 13;
  public static final int RCURLY = 33;
  public static final int IMPORT = 8;
  public static final int MODULE = 9;
  public static final int COLON = 36;
  public static final int ELSE = 22;
  public static final int READ = 56;
  public static final int ENUM = 11;
  public static final int WHILE = 14;
  public static final int ANDPERSAND = 37;
  public static final int DEFAULT = 16;
  public static final int ITER = 58;
  public static final int STRING = 3;
  public static final int DIFF = 45;
  public static final int STRUCT = 18;
  public static final int VAR = 29;
  public static final int PRINT = 55;
}

